name: 'Nyrkiö Change Detection'
author: 'Nyrkiö Oy <https://nyrkio.com/product>'
description: 'GitHub Action for integrating Nyrkiö Change Detection with your Continuous Benchmarking results.'
branding:
  icon: 'trending-up'
  color: 'red'
inputs:
  name:
    description: 'Name of the benchmark. This value must be identical among all benchmarks'
    required: true
    default: 'Benchmark'
  tool:
    description: 'Tool to use get benchmark output. One of "cargo", "criterion", "go", "gotpc", "benchmarkjs", "pytest", "googlecpp", "catch2", "julia", "benchmarkdotnet", "time", "customBiggerIsBetter", "customSmallerIsBetter", "nyrkioJson"'
    required: true
  output-file-path:
    description: 'A path to file which contains the benchmark output. (For nyrkioJson, a directory of JSON files.)'
    required: true
  gh-pages-branch:
    description: 'Branch for gh-pages'
    required: false
    default: 'gh-pages'
  gh-repository:
    description: 'Url to an optional different repository to store benchmark results'
    required: false
  benchmark-data-dir-path:
    description: 'Path to directory which contains benchmark files on GitHub pages branch'
    required: false
    default: 'dev/bench'
  github-token:
    description: 'GitHub API token to pull/push GitHub pages branch and deploy GitHub pages. For public repository, this must be personal access token for now. Please read README.md for more details'
    required: false
  ref:
    description: 'optional Ref to use when finding commit'
    required: false
  auto-push:
    description: 'Push GitHub Pages branch to remote automatically. This option requires github-token input'
    required: false
    default: false
  skip-fetch-gh-pages:
    description: 'Skip pulling GitHub Pages branch before generating an auto commit'
    required: false
    default: false
  comment-always:
    description: 'Leave a comment with benchmark result comparison. To enable this feature, github-token input must be given as well'
    required: false
    default: false
  summary-always:
    description: 'Leave a job summary with benchmark result comparison'
    required: false
    default: false
  save-data-file:
    description: 'Save the benchmark data to external file'
    required: false
    default: true
  comment-on-alert:
    description: 'Leave an alert comment when current benchmark result is worse than previous. Threshold is specified with alert-threshold input. To enable this feature, github-token input must be given as well'
    required: false
    default: false
  alert-threshold:
    description: 'Threshold which determines if an alert should happen or not. Percentage value such as "150%". For example, 150% means that an alert happens when current benchmark result is 1.5x worse than previous'
    required: false
    default: '200%'
  fail-on-alert:
    description: 'Workflow fails when alert comment happens'
    required: false
    # Note: Set to false by default since this action does not push to remote by default. When workflow
    # fails and auto-push is not set, there is no chance to push the result to remote.
    default: false
  fail-threshold:
    description: 'Threshold which determines if the current workflow fails. Format is the same as alert-threshold input. If this value is not specified, the same value as alert-threshold is used'
    required: false
  alert-comment-cc-users:
    description: 'Comma separated GitHub user names which start with @ (e.g. "@foo,@bar"). They will be mentioned in commit comment for alert.'
    required: false
  external-data-json-path:
    description: 'JSON data file for storing benchmark results. When this input is set, github-action-benchmark no longer uses Git branch to store data. Instead, it reads and appends benchmark data from/to the file. User must store the file anywhere'
    required: false
  max-items-in-chart:
    description: 'Max data points in a benchmark chart to avoid making the chart too busy. Value must be unsigned integer. No limit by default'
    required: false
  nyrkio-enable:
    description: 'Use Nyrkiö (web service) to store your benchmark results and to find statistically significant change points.'
    required: false
    default: true
  nyrkio-token:
    description: 'A JWT token from your nyrkio.com settings page'
    required: false
  nyrkio-api-root:
    description: 'The root URL for a Nyrkiö API'
    required: false
    default: 'https://nyrkio.com/api/v0/'
  nyrkio-public:
    description: 'Publish these benchmark results at nyrkio.com/public. (Recommended for open source projects.)'
    required: false
    default: false
  nyrkio-org:
    description: 'The name of a github org where you have installed Nyrkiö. See https://nyrkio.com/user/settings#nyrkio-settings-userinfo'
    required: false
  nyrkio-settings-pvalue:
    description: 'The p-value used to determine if a change in benchmark results is statistically significant. Example: 1% (If specified, will be applied to all your nyrkio.com test results.)'
    required: false
  nyrkio-settings-threshold:
    description: 'Threshold percentage below which changes will be ignored. Example: 2% (If specified, will be applied to all your nyrkio.com test results.)'
    required: false
  never-fail:
    description: "Don't fail the workflow, ever. Not even if the action itself fails due to bugs or network or whatever."
    required: false
    default: false
runs:
  # using: 'composite'
  # steps:
  #     # - uses: actions/setup-node@v4
  #     #   with:
  #     #     node-version: 20
  #     #     cache: 'npm'
  #     - name:  Install dependencies & compile typescript
  #       shell: bash
  #       run:   cd ${{ github.action_path }} && npm install && npm run build
  #
  #     - name:  Run action
  #       shell: bash
  #       run:   cd ${{ github.action_path }} && node dist/src/index.js
  #       # shell: bash
  #       # run:   cd ${{ github.action_path }} && node dist/src/index.js
  using: node20
  main: action.js
