name: 'Benchmark extract and transform'
author: 'Cryspen <https://github.com/cryspen>'
description: 'Extract and transform `cargo` and other benchmark data for visualization'
branding:
  icon: 'fast-forward'
  color: 'blue'

inputs:
  name:
    description: 'Name of the benchmark. This value must be identical among all benchmarks'
    required: true
    default: 'Benchmark'
  tool:
    description: 'Tool to use get benchmark output. One of "cargo"...'
    required: true
  platform:
    description: 'A string describing the platform'
    required: true
  output-file-path:
    description: 'A path to file which contains the benchmark output'
    required: true
  json-out-path:
    description: 'A path to the file where the output of the action should be written'
    required: true

runs:
  using: 'node20'
  main: 'dist/src/index.js'
