name: Catch2 C++ Example
on:
  push:
    branches:
      - master

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run Catch2 C++ Benchmark Framework example (v2.x)
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Build and run benchmarks with Catch2
        run: |
          cd examples/catch2_v2
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . --config Release
          ./Catch2_bench | tee ../benchmark_result.txt

      - name: Store benchmark result
        uses: nyrkio/change-detection@v1
        with:
          name: Catch2 Benchmark
          tool: 'catch2'
          output-file-path: examples/catch2_v2/benchmark_result.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          nyrkio-enable: false

      - name: Store benchmark result - separate results repo
        uses: nyrkio/change-detection@v1
        with:
          name: Catch2 Benchmark
          tool: 'catch2'
          output-file-path: examples/catch2_v2/benchmark_result.txt
          github-token: ${{ secrets.BENCHMARK_ACTION_BOT_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          gh-repository: 'github.com/nyrkio/github-action-benchmark-results'
          nyrkio-enable: false
