name: Go TPC
on:
  push:
    branches:
      - master

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run minimal steps to run change-detection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
      - name: Analyze Go TPC results with Nyrkiö
        uses: nyrkio/change-detection@HEAD
        with:
          tool: 'gotpc'
          output-file-path: test/gotpc/output1.txt
          # Pick up your token at https://nyrkio.com/docs/getting-started
          # Then head to https://github.com/USER_OR_ORG/PROJECT/settings/secrets/actions
          # Store the token you just created as a Repository secret. We'll use the variable name `secrets.NYRKIO_JWT_TOKEN` for it below.
          nyrkio-token: ${{ secrets.NYRKIO_JWT_TOKEN }}
          name: nyrkio/change-detection/gotpc-example
          fail-on-alert: true
