name: Example for minimal setup
on:
  # NOTE! Do NOT add any other "on", because this workflow has permission to write to the repo!
  push:
    branches:
      - master

permissions:
  # permission to update benchmark contents in gh-pages branch
  contents: "write"

jobs:
  benchmark:
    name: Run benchmark and save results
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: "stable"
      - name: Run benchmark and stores the output to a file
        run: cd examples/go && go test -bench 'BenchmarkFib' | tee output.txt
      - name: Get JSON for benchmark
        uses: benchmark-action/github-action-benchmark@v1
        with:
          # What benchmark tool the output.txt came from
          tool: 'go'
          # Where the output from the benchmark tool is stored
          output-file-path: output.txt
          # Updates this file
          external-data-json-path: ./cache/benchmark-data.json
          # Workflow will fail when an alert happens
          fail-on-alert: true
          # Writes to gh-pages-branch
          auto-push: "true"
      - name: Save JSON in cache
        uses: actions/cache/save@v5
        with:
          path: ./cache/benchmark-data.json
          # Save with commit hash to avoid "cache already exists"
          key: "${{ github.sha }}-${{ runner.os }}-go-benchmark"