name: Example for minimal setup
on:
  push:
    branches:
      - master

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run minimal steps to run github-action-benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4
        with:
          go-version: "stable"
      - name: Run benchmark
        run: cd examples/go && go test -bench 'BenchmarkFib' | tee output.txt
      - name: Download previous benchmark data
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@52576c92bccf6ac60c8223ec7eb2565637cae9ba # v1
        with:
          tool: 'go'
          output-file-path: examples/go/output.txt
          external-data-json-path: ./cache/benchmark-data.json
          fail-on-alert: true
