name: NyrkioJson Example
on:
  push:
    branches:
      - master

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run NyrkioJson (pass through) example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Nyrkiö Json - just send it as is
        uses: nyrkio/change-detection@HEAD
        with:
          # This plus the filename is the full test name sent to nyrkio
          name: nyrkio/change-detection/master/nyrkioJson
          tool: 'nyrkioJson'
          output-file-path: examples/nyrkioJson/benchmark-results

          # What to do if a change is immediately detected by Nyrkiö.
          # Note that smaller changes are only detected with delay, usually after a change
          # persisted over 2-7 commits. Go to nyrkiö.com to view those or configure alerts.
          # Note that Nyrkiö will find all changes, also improvements. This means fail-on-alert
          # on pull events isn't compatible with this workflow being required to pass branch protection.
          fail-on-alert: false
          comment-on-alert: true
          comment-always: false

          # Nyrkiö configuration
          nyrkio-enable: true

          # Pick up your token at https://nyrkio.com/docs/getting-started
          # Then head to https://github.com/USER_OR_ORG/PROJECT/settings/secrets/actions
          # Store the token you just created as a Repository secret. We'll use the variable name `secrets.NYRKIO_JWT_TOKEN` for it below.
          nyrkio-token: ${{ secrets.NYRKIO_JWT_TOKEN }}

          # You may not want share the NYRKIO_JWT_TOKEN token with pull requests, for example.
          # In that case this task would unnecessarily fail for random contributors. Don't want that:
          never-fail: true

          # Make results and change points public, so that any oss contributor can see them
          nyrkio-public: true
          nyrkio-settings-pvalue: 0.01
          nyrkio-settings-threshold: 2%
